import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
    backgroundColor: '#f5f5f5',
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 10,
    color: '#222',
    fontFamily: 'sans-serif',
  },
  helper: {
    fontSize: 16,
    color: '#666',
    alignSelf: 'center',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'sans-serif',
  },
  barcode: {
    fontWeight: 'bold',
    color: '#007bff',
    fontSize: 18,
    fontFamily: 'sans-serif',
  },
  button: {
    backgroundColor: '#288392',
    padding: 18,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 40,
    marginTop: 30,
    elevation: 2,
  },
  buttonDisabled: {
    backgroundColor: '#a0c4ff',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
    fontFamily: 'sans-serif',
  },
  visibleInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 6,
    marginVertical: 20,
    fontSize: 18,
    fontFamily: 'monospace',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  messageItem: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 6,
    marginBottom: 10,
    elevation: 1,
    fontFamily: 'sans-serif',
  },
  emptyState: {
    textAlign: 'center',
    color: '#aaa',
    fontSize: 16,
    marginVertical: 30,
    fontFamily: 'sans-serif',
  },
  prevButton: {
    backgroundColor: '#eee',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  prevButtonText: {
    color: '#288392',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'sans-serif',
  },
  reloadButton: {
    alignSelf: 'center',
    marginBottom: 10,
    padding: 10,
    paddingHorizontal: 20,
    backgroundColor: '#e0f7fa',
    borderRadius: 24,
  },
  reloadButtonText: {
    color: '#288392',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'sans-serif',
  },
  arrowButton: {
    marginLeft: 8,
    padding: 8,
    backgroundColor: '#e0f7fa',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  magnifierIcon: {
    width: 72,
    height: 72,
    alignSelf: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  magnifierCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 6,
    borderColor: '#288392',
    position: 'absolute',
    top: 0,
    left: 12,
  },
  magnifierHandle: {
    width: 24,
    height: 6,
    backgroundColor: '#288392',
    position: 'absolute',
    bottom: 10,
    right: 0,
    borderRadius: 3,
    transform: [{ rotate: '45deg' }],
  },
  checkmark: {
    fontSize: 48,
    color: '#288392',
    alignSelf: 'center',
    marginBottom: 10,
    fontWeight: 'bold',
  },
});

export default styles;